eloja/urls.py
from django.contrib import admin
from django.urls import path, include
from manager.views import Index

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    # path('/')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import IndexM_View, ProdutoCreate, ProdutoList, ProdutoUpdate 
from .views import Catalogo, Checkin, ProdutoCompra, Sucesso
from .views import cart_add, cart_detail, cart_remove
# from .views import form_CriarProduto
# from . import views

app_name = 'manager'

# pk permite acessar, é a chave primária/id do produto em questão

urlpatterns = [
    path('', IndexM_View.as_view(), name='index'),
    path('cadastro/', ProdutoCreate.as_view(), name='add'),
    path('lista/', ProdutoList.as_view(), name= 'list'),
    path('att/<int:pk>/', ProdutoUpdate.as_view(), name='att'),
    
    path('catalogo/', Catalogo.as_view(), name= 'catalog'),
    path('checkin/', Checkin.as_view(), name= 'checkin'),
    path('final/', Sucesso.as_view(), name= 'final'),

    path('produto/<int:pk>', ProdutoCompra.as_view(), name= 'produto'),

    path('cart/', cart_detail, name="cart"),
    path('add/<int:pk>/', cart_add, name="cartadd"),
    path('del/<int:pk>/', cart_remove, name="cartdel"),

    # path('cadastro/', form_CriarProduto, name='manager_produto'),
    # path('editar/', form_editarproduto, name='form_criarproduto'),
    # path('lista/', lista_produtos, name='lista_produtos'),
]

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title> Indice - Eh-Loja </title>

  {% comment %} {% if url 'index' %}
  <div>
    <a href="{% url 'manager:index' %}"> 
      <h4> Seção do Gerente </h4>
    </a>
   </div>
  {% else %}
      <h4>Sem link, otario</h4>
  {% endif %} {% endcomment %}
</head>

<body style="background-color:#0d0d0d; color:white;">
   <h1> Loja Virtual: Eh-Loja </h1>
   <hr>

   <div>
    <a href="{% url 'manager:index' %}"> 
      <h4> Seção do Gerente </h4>
    </a>
   </div>

   <div>
    <a href="{% url 'manager:catalog' %}"> 
      <h4> Catálogo para Clientes </h4>
    </a>
   </div>

</body>

</html>