eloja/urls.py
from django.contrib import admin
from django.urls import path, include
from manager.views import Index

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    # path('/')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import IndexM_View, ProdutoCreate, ProdutoList, ProdutoUpdate 
from .views import Catalogo, Checkin, ProdutoCompra, Sucesso
from .views import cart_add, cart_detail, cart_remove
# from .views import form_CriarProduto
# from . import views

app_name = 'manager'

# pk permite acessar, é a chave primária/id do produto em questão

urlpatterns = [
    path('', IndexM_View.as_view(), name='index'),
    path('cadastro/', ProdutoCreate.as_view(), name='add'),
    path('lista/', ProdutoList.as_view(), name= 'list'),
    path('att/<int:pk>/', ProdutoUpdate.as_view(), name='att'),
    
    path('catalogo/', Catalogo.as_view(), name= 'catalog'),
    path('checkin/', Checkin.as_view(), name= 'checkin'),
    path('final/', Sucesso.as_view(), name= 'final'),

    path('produto/<int:pk>', ProdutoCompra.as_view(), name= 'produto'),

    path('cart/', cart_detail, name="cart"),
    path('add/<int:pk>/', cart_add, name="cartadd"),
    path('del/<int:pk>/', cart_remove, name="cartdel"),

    # path('cadastro/', form_CriarProduto, name='manager_produto'),
    # path('editar/', form_editarproduto, name='form_criarproduto'),
    # path('lista/', lista_produtos, name='lista_produtos'),
]

templates/venda/carrinho.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}

<html lang="pt-br">

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title> Indice - Eh-Loja </title>
</head>

<body style="background-color:#0d0d0d; color:white;">
   <h1> Meu Carrinho </h1>
   <a href="{% url 'manager:catalog' %}"> Voltar </a>
   <hr>

   {% if messages %}
   {% for message in messages %}
    <div class="success">
      {{ message }}
    </div>
   {% endfor %}
   {% endif %}

   <div class="container my-3 table-responsive">

    {% if cart %}
    <table class="table">
        <thead>
            <tr class="bg-light">
                <th scope="col">Produto</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Preço Unitário</th>
                <th scope="col">Preço Total</th>
                <th scope="col">Ações</th>
            </tr>
    </thead>
    <tbody >
      {% for item in cart %}
      {% with product=item.produto %}
      <tr>
          <td class="align-middle"> {{ item.produto }} </td>
          <td class="align-middle"> {{ item.quantidade }}</td>
          <td class="align-middle">R$ {{ item.preco }}</td>
          <td class="align-middle">R$ {{ item.preco_total }}</td>
          <td class="align-middle text-right">

            <form action="{% url 'manager:cartdel' product.id %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="Remover">
            </form>
        </td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="bg-light" style="border-top-width=5px;">
          
          <td class="font-weight-bold">Total</td>
          <td></td>
          <td></td>
          <td class="font-weight-bold">R$ 
            {{ cart.get_preco_total }}
          </td>
          <td></td>
      </tr>
    </table>
    {% else %}
      <p>O carrinho está vazio!</p>
    {% endif %}
    <p class="text-right">
      <a class=" btn btn-primary" href="{% url 'manager:catalog' %}">
          Continuar comprando
      </a>

      <a class="btn btn-success {% if not cart %}disabled {% endif %}" 
      href="{% url 'manager:checkin' %}">
          Confirmar pagamento
      </a>

    </p>
  

</body>

</html>

templates/venda/cartadd.html
<!DOCTYPE html>
<html lang="pt-br">

{% load static %}

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title> Detalhes do Produto </title>
</head>

<body style="background-color:#0d0d0d; color:white;">
   <h1> Detalhes da Compra </h1>

    <div>
    <a href="{% url 'manager:cart' %}"> Meu Carrinho </a>
    </div>
    <div>
    <a href="{% url 'manager:catalog' %}"> Voltar </a>
    </div> 
    
   <hr>
   
   
   <div>
      <h4> Detalhes do produto </h4>

      <div class="container">
        <div class="row">
      
            <div class="col-lg-9">
              {% comment %} produto ou object funcionam {% endcomment %}
                <h1>{{ product }}</h1>  
            </div>
        </div>
    </div>



   </div>
  

</body>

</html>

templates/venda/catalogo.html
<!DOCTYPE html>
<html lang="pt-br">

{% load static %}
{% comment %} {% load media %} {% endcomment %}

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title> Indice - Eh-Loja </title>
</head>

<body style="background-color:#0d0d0d; color:white;">
   <h1> Loja Virtual: Eh-Loja </h1>

   <div>
    <a href="{% url 'manager:cart' %}"> Meu Carrinho </a>
    </div>
    <div>
    <a href="{% url 'index' %}"> Voltar </a>
    </div> 
    
   <hr>
   
   
   <div>
      <h4> Lista de Produtos </h4>
      <ul>
        {% for produto in object_list %}
          {% if produto.disponivel == True %}
            <hr>
            <li> {{produto.nome}} </li>
            <a href="{% url 'manager:produto' produto.id %}">
            Comprar
            </a> 
              {% comment %} <a href="{% url 'manager:att' pk=produto.id %}">  Comprar </a>  {% endcomment %}
              <ul> 
                <div>   
                  <li> 
                    <div>
                    {% if produto.imagem %}
                      {% comment %} <img class="container-fluid" src="../../media/imgs/{{produto.image}}" alt="" style="width:100px;height:100px;"> {% endcomment %}
                      <img class="card-img-top" src="../..{{produto.imagem.url}}" alt="" style="width:100px;height:100px;">
                    {% else %}
                      <img class="card-img-top" src="{% static 'default.png' %}" alt="">
                    {% endif %}
                    </div>
                  </li>
                  {% comment %} <li>Imagem: {{produto.imagem}}</li> {% endcomment %}
                  <li>Preço: {{produto.preco_unitario}}</li>
                  <li>Estoque atual: {{produto.estoque}}</li> 
                </div>
              </ul>
          {% endif %}
        {% endfor %}
       </ul>

   </div>
  

</body>

</html>

templates/venda/checkin.html
<!DOCTYPE html>
<html lang="pt-br">

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title>Página de Compra</title>
</head>

<body style="background-color:#0d0d0d; color:white;">
  <h1> Check-in da Venda </h1>

  {% if messages %}
   {% for message in messages %}
    <div class="success">
      {{ message }}
    </div>
   {% endfor %}
   {% endif %}

  <div>
    <a href="{% url 'manager:cart' %}"> Meu Carrinho </a>
  </div>
  <div>
    <a href="{% url 'manager:catalog' %}"> Voltar ao Catálogo </a>
  </div> 
    
  <hr>

  
  <form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }} 
     {% comment %} <input type="reset" value="Apagar dados" href="{% url 'manager:catalog' %}"> {% endcomment %}
     <input type="submit" value="Confirmar compra" href="{% url 'manager:final' %}"> 
     
  </form> 
  <p> Valor a pagar: R$ {{ valorCarrinho }}0 </p>
  
  {% comment %} {{ cart.get_preco_total }} {% endcomment %}
  {% comment %} {% if cart %} 
    <p> Texto </p>
    <div> 

      <ul>
        {% for item in cart %}
         {% with product=item.produto %}}
          <li> {{item.produto}} </li>
            <ul> 
              <div>   
                <li> {{item.quantidade}} x {{item.preco}} = {{item.preco_total}}</li>
                {% comment %} <li>Preço: {{item.preco_total}}</li> {% endcomment %}
              {% comment %} </div>
            </ul>
      {% endwith %} 
        {% endfor %}

      </ul>
      <p>
        {{ cart.get_preco_total }}
      </p>
    </div> 
 {% endif %} {% endcomment %}
    
{% comment %} {% with product=item.produto %} {% endcomment %}
            {% comment %} <p class="align-middle"> {{ item.produto }}</p>
            <p class="align-middle"> {{ item.quantidade }}</p> {% endcomment %}
          {% comment %} {% endwith %} {% endcomment %}
    

   {% comment %} <p> 

   </p> {% endcomment %}


   <p class="text-right">
    <a class=" btn btn-primary" href="{% url 'manager:catalog' %}">
        Continuar comprando
    </a>

  </p>


</body>

</html>

templates/venda/produto.html
<!DOCTYPE html>
<html lang="pt-br">

{% load static %}

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title> Detalhes do Produto </title>
</head>

<body style="background-color:#0d0d0d; color:white;">
   <h1> Detalhes da Compra </h1>

    <div>
    <a href="{% url 'manager:cart' %}"> Meu Carrinho </a>
    </div>
    <div>
    <a href="{% url 'manager:catalog' %}"> Voltar </a>
    </div> 
    
   <hr>
   
   
   <div>
      <h4> Detalhes do produto </h4>

      <div class="container">
        <div class="row">
            <div class="col-lg-3 mb-3 mb-lg-0">
                {% if object.imagem %}
                  <img class="container-fluid" src="../../..{{object.imagem.url}}" alt="" style="width:100px;height:100px;">
                {% else %}
                  <img class="card-img-top" src="{% static 'default.png' %}" alt="">
                {% endif %}
            </div>
            <div class="col-lg-9">
              {% comment %} produto ou object funcionam {% endcomment %}
                <h1 class="font-weight-bold">{{ object.nome }}</h1>  
                <h2>Unidade: R$ {{ object.preco_unitario }}</h2>
                <h5>Estoque: {{ object.estoque }}</h5>
                <form class="form-group" action="{% url 'manager:cartadd' object.id %}" method="post">
                    <p class="form-inline">
                        {{ form.as_p }}
                    </p>
                    {% csrf_token %}
                    <input class="btn btn-success" type="submit" value="Adicionar ao Carrinho"
                    >
                </form>
            </div>
        </div>
    </div>



   </div>
  

</body>

</html>

templates/venda/sucesso.html
<!DOCTYPE html>
<html lang="pt-br">

<head style="background-color:#0d0d0d; color:white;">
  <meta charset="UTF-8" />
  <meta name="viewport" 
  content="width=device-width, initial-scale=1.0">
  <title>Compra finalizada!</title>
</head>

<body style="background-color:#0d0d0d; color:white;">

   <h1> Compra Finalizada! </h1>

   {% if messages %}
   {% for message in messages %}
    <div class="success">
      {{ message }}
    </div>
   {% endfor %}
   {% endif %}

   <h3>
   Sua compra foi processada, {{venda.nome}}!
   Valor final da compra: R$ {{venda.valor_final}}.

   Volte sempre!
   </h3>
   
   <hr>
   
   <div>
    <a href="{% url 'manager:catalog' %}"> Voltar ao Catálogo </a>
   </div> 

   <div>
    <a href="{% url 'index' %}"> Voltar ao Início </a>
   </div> 
   
</body>

</html>